"""add new table and chaage on student

Revision ID: 70c268e7c443
Revises: 5876be4f3bb2
Create Date: 2023-08-14 16:00:29.483019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c268e7c443'
down_revision = '5876be4f3bb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_lastname', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_unique_constraint(None, 'student', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_table('user')
    # ### end Alembic commands ###
