"""in AuthorModel add UniqueConstraint

Revision ID: ba4f31230a9f
Revises: ffbfe9295204
Create Date: 2023-07-15 19:04:46.779282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4f31230a9f'
down_revision = 'ffbfe9295204'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'author', ['first_name', 'last_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='unique')
    # ### end Alembic commands ###
