"""change table book_copies, add nullable=True

Revision ID: d5d3170a5613
Revises: ba4f31230a9f
Create Date: 2023-07-15 23:33:02.723689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d3170a5613'
down_revision = 'ba4f31230a9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_copies', 'isbn',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('book_copies', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_copies', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book_copies', 'isbn',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    # ### end Alembic commands ###
