from os import environ

DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_USER = "ham"
DATABASE_PASS = "002110280"
DATABASE_NAME = "library_1"

CONNECTION_STRING = f"postgresql://{DATABASE_USER}:{DATABASE_PASS}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
